config/routes.rb
# frozen_string_literal: true

Rails.application.routes.draw do
  resources :articles

  root 'home#index'

  namespace :api do
    resources :articles
  end
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/article.rb
class Article < ApplicationRecord
end

app/controllers/api/articles_controller.rb
# frozen_string_literal: true

module Api
  class ArticlesController < ApplicationController
    def index
      render json: Article.all
    end

    def show
      article = find_article(params[:id])
      render json: article
    end

    def create
      article = Article.new(article_params)
      article.save
      render json: { message: 'Article has been published' }
    end

    def update
      article = find_article(params[:id])
      article.update(article_params)
      render json: { message: 'Article has been updated' }
    end

    def destroy
      article = find_article(params[:id])
      article.destroy
      render json: { articles: Article.all }
    end

    private

    def article_params
      params.require(:article).permit(:title, :body)
    end

    def find_article(id)
      Article.find_by(id: id)
    end
  end
end

app/controllers/application_controller.rb
# frozen_string_literal: true

class ApplicationController < ActionController::Base
  skip_before_action :verify_authenticity_token
end

app/controllers/articles_controller.rb
# frozen_string_literal: true

class ArticlesController < ApplicationController
  def index; end

  def new; end

  def edit
    @article = Article.find_by(id: params[:id])
  end
end

app/controllers/home_controller.rb
class HomeController < ApplicationController
  def index
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/home_helper.rb
module HomeHelper
end

app/views/articles/edit.html.erb
<div class="mb-4 text-right">
  <%= link_to 'Back to article lists', articles_path %>
</div>

<div class="pb-2">
  <h5>Update Article</h5>
</div>
<article-form id="<%= @article.id %>"></article-form>

app/views/articles/index.html.erb
<div class="mb-4">
  <%= link_to 'New Article', new_article_path %>
</div>

<article-list></article-list>

app/views/articles/new.html.erb
<div class="mb-4 text-right">
  <%= link_to 'Back to article lists', articles_path %>
</div>

<div class="pb-2">
  <h5>Create new article</h5>
</div>

<article-form></article-form>

app/views/home/index.html.erb
<h1>Home#index</h1>
<p>Find me in app/views/home/index.html.erb</p>
{{ message }}
<app></app>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Sample CRUD Vue-Rails</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag    'application', media: 'all' %>
    <%= javascript_include_tag 'application' %>
    <%= javascript_pack_tag 'application' %>
    <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/font-awesome/4.7.0/css/font-awesome.min.css">
  </head>

  <body>
    <div id="app" class="container my-4">
      <div class="row">
        <div class="col-md-5 m-auto border-right border-left">
          <%= yield %>
        </div>
      </div>
    </div>
  </body>
</html>